
# This is the python code to get the concept about form feed symbols

print("\x0a")
print("\x0b")
print("\x0c")
print("\x0d")
print("\x0e")
print("\x0f")
#print("\x0g")
#print("\x0h")
#print("\x0i")
#print("\x0j")
#print("\x0k")
print("\x0l")
print("\x0m")
print("\x0n")
print("\x0o")
print("\x0p")
print("\x0q")
print("\x0r")
print("\x0s")
print("\x0t")
print("\x0u")
print("\x0v")
print("\x0w")
#print("\x0x")
#print("\x0y")
#print("\x0z")